### ISSUE TITLE
modid.mixins.json causes name conflict

### ISSUE THREAD

**Issue by Sturmlilie** [HyperPigeon/MoreTotems#1]
When I load this mod together with end-rebellion, I get a mixin related crash on startup. According to the fabric discord, `modid.mixins.json` should be renamed to something sensible to fix it.

**Comment by HyperPigeon** [comment]
Sorry for the late reply,

The issue should be fixed now. Thanks for letting me know.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Sturmlilie** [comment]
Solved, thanks!
